export const PERMISSIONS = {
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    VIEW_INVENTORY: 'VIEW_INVENTORY',
    MANAGE_INVENTORY: 'MANAGE_INVENTORY',
    VIEW_REPORTS: 'VIEW_REPORTS',
    VIEW_PRODUCTS: 'VIEW_PRODUCTS',
    MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
    VIEW_CLIENTS: 'VIEW_CLIENTS',
    MANAGE_CLIENTS: 'MANAGE_CLIENTS',
    VIEW_CASH: 'VIEW_CASH',
    MANAGE_CASH: 'MANAGE_CASH',
    MANAGE_USERS: 'MANAGE_USERS',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export const ALL_PERMISSIONS: string[] = Object.values(PERMISSIONS);
