export const PERMISSIONS = {
  // dashboard
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',

  // tiendas
  VIEW_STORES: 'VIEW_STORES',
  MANAGE_STORES: 'MANAGE_STORES',
  CHANGE_STORE_LOGO: 'CHANGE_STORE_LOGO',

  // caja
  VIEW_CASH: 'VIEW_CASH',
  MANAGE_CASH: 'MANAGE_CASH',
  VIEW_ALL_CASH_HISTORY: 'VIEW_ALL_CASH_HISTORY',
  VIEW_OWN_CASH_HISTORY: 'VIEW_OWN_CASH_HISTORY',
  PRINT_CASH_CLOSURE: 'PRINT_CASH_CLOSURE',

  // ventas
  VIEW_ORDERS: 'VIEW_ORDERS',
  MANAGE_ORDERS: 'MANAGE_ORDERS',
  DETAIL_ORDERS: 'DETAIL_ORDERS',
  VIEW_ALL_ORDERS_HISTORY: 'VIEW_ALL_ORDERS_HISTORY',
  VIEW_OWN_ORDERS_HISTORY: 'VIEW_OWN_ORDERS_HISTORY',

  // servicios
  VIEW_SERVICES: 'VIEW_SERVICES',
  VIEW_ALL_SERVICES: 'VIEW_ALL_SERVICES',
  DETAIL_SERVICES: 'DETAIL_SERVICES',
  MANAGE_SERVICES: 'MANAGE_SERVICES', //se usa para crear servicios personalizados

  // productos
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  MANAGE_PRICES: 'MANAGE_PRICES',
  VIEW_PRODUCT_COST: 'VIEW_PRODUCT_COST',
  VIEW_PRODUCT_PRICES: 'VIEW_PRODUCT_PRICES',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',

  // inventario
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  START_PHYSICAL_INVENTORY: 'START_PHYSICAL_INVENTORY',

  // almacenes
  VIEW_WAREHOUSES: 'VIEW_WAREHOUSES',
  MANAGE_WAREHOUSES: 'MANAGE_WAREHOUSES',

  // clientes
  VIEW_CLIENTS: 'VIEW_CLIENTS',
  MANAGE_CLIENTS: 'MANAGE_CLIENTS',

  // empleados
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',
  CONVERT_EMPLOYEE_TO_USER: 'CONVERT_EMPLOYEE_TO_USER',
  RECREATE_EMPLOYEE: 'RECREATE_EMPLOYEE',

  // proveedores
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  DELETE_SUPPLIERS: 'DELETE_SUPPLIERS',

  // ordenes de suministro
  VIEW_SUPPLY_ORDERS: 'VIEW_SUPPLY_ORDERS',
  CREATE_SUPPLY_ORDER: 'CREATE_SUPPLY_ORDER',
  EDIT_EMITTED_SUPPLY_ORDER: 'EDIT_EMITTED_SUPPLY_ORDER',
  APPROVE_SUPPLY_ORDER: 'APPROVE_SUPPLY_ORDER',
  RECEIVE_SUPPLY_ORDER: 'RECEIVE_SUPPLY_ORDER',
  CANCEL_SUPPLY_ORDER: 'CANCEL_SUPPLY_ORDER',

  // usuarios y accesos
  VIEW_USERS: 'VIEW_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  DELETE_USERS: 'DELETE_USERS',

  // soporte técnico
  VIEW_SUPPORT: 'VIEW_SUPPORT',
  MANAGE_SUPPORT: 'MANAGE_SUPPORT',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
export const ALL_PERMISSIONS: string[] = Object.values(PERMISSIONS);
